- hosts: localhost
  vars_files:
    - ./defaults.yaml
  vars:
    homebrew_environment: "{{ {'SUDO_ASKPASS': lookup('env', 'SUDO_ASKPASS')} if lookup('env', 'SUDO_ASKPASS') else {} }}"
  pre_tasks:
    - import_tasks: ansible/tasks/platform.yaml
      tags: [always]

    - name: Show selected package inventories
      ansible.builtin.debug:
        var: package_files
      tags: [never, packages]

    - import_tasks: ansible/tasks/validation.yaml
      when: "ansible_run_tags != ['packages']"
      tags:
        - always

    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
      environment: "{{ homebrew_environment }}"
      tags:
        - install
        - core
        - cli
        - gui
  tasks:
    - import_tasks: ansible/tasks/security.yaml
      when: manage_ssh_config | bool
    - import_tasks: ansible/tasks/git-setup.yaml
    - import_tasks: ansible/tasks/cli-tools.yaml
    - import_tasks: ansible/tasks/mac/remote-login.yaml
      when: platform == 'mac' and manage_remote_login | bool
    - import_tasks: ansible/tasks/mac/gui-tools.yaml
      when: platform == 'mac'
    - import_tasks: ansible/tasks/zsh.yaml
    - import_tasks: ansible/tasks/mac/app-store-apps.yaml
      when: platform == 'mac'
    - import_tasks: ansible/tasks/mac/osx.yaml
      when: platform == 'mac'
    - import_tasks: ansible/tasks/node.yaml
    - import_tasks: ansible/tasks/dotfiles.yaml
      when: install_dotfiles | bool
    - import_tasks: ansible/tasks/mac/dock.yaml
      when: platform == 'mac'
