ssh_agent_socket: "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
manage_ssh_config: true
install_dotfiles: true
pnpm_home: "{{ ansible_facts['env']['HOME'] }}/Library/pnpm"
shell_path: /bin/zsh
