# Personal-only packages can be added here.

[packages]
# Proton apps
"brew-cask:proton-mail" = "latest"
"brew-cask:proton-drive" = "latest"

# Communication
"brew-cask:discord" = "latest"

# Media
"brew-cask:vlc" = "latest"
"brew-cask:downie" = "latest"
